### PR TITLE
Add docker for Numbat

### PR DESCRIPTION
**Pull request by evanbiederstedt**
* Dockerfiles for both base R and RStudio
* Added Docker images to Dockerhub
* Added details to the README

Feel free to revise the README, @teng-gao and check that everything works as expected

### CODE REVIEW

**Comment by teng-gao** [comment]
Are `cell-snplite` and `eagle2` included in the container?
What about phasing reference files?

**Comment by evanbiederstedt** [comment]
> Are cell-snplite and eagle2 included in the container?

This should be in the current README that users need to install these tools (and the associated dependencies) in order to use this package. 

The dependencies would be: https://cellsnp-lite.readthedocs.io/en/latest/install.html#step-0-install-dependencies

**Comment by teng-gao** [comment]
Yes, it would be nice to have them in the container. Currently, this is included in the instructions [here](https://kharchenkolab.github.io/numbat/articles/numbat.html#prerequisites).

**Comment by evanbiederstedt** [comment]
> Currently, this is included in the instructions [here](https://kharchenkolab.github.io/numbat/articles/numbat.html#prerequisites).

Yeah, but I'm saying you need this in the README. You need to be explicit as well in terms of the installation of these tools. 

For instance, you need to tell the user that `eagle` needs to be accessible as a command line tool in their path. You should tell users how to do this. 

That means repeating some of the installation instructions for `cell-snplite` as well. 

You'll need to give the commands for users to add this to their bash profile (probably) to make them immediately accessible.

**Comment by evanbiederstedt** [comment]
We could put the phasing files in the Docker container. It will make the container more heavy, but that's fine.

**Comment by teng-gao** [comment]
> We could put the phasing files in the Docker container. It will make the container more heavy, but that's fine.

Yes, that'd be good. The users would have to download them either way.

**Comment by evanbiederstedt** [comment]
This should be working as you'd expect now

Downloading the reference panels was a bit painful, so I'd ask the users to do this. 

Steps forward:

(1) We need a realistic command here: 
```
Rscript pileup_and_phase.R --label, --samples, --bams, --gmap, --snpvcf, --paneldir, --outdir, --ncores
```

Users should probably put these input files into `/work`

(2) We should move the stuff from `README` into the documentation

**Comment by teng-gao** [comment]
Thanks for the updates. I will add a dedicated page in the documentation called "Running Numbat using Docker".

**Comment by evanbiederstedt** [comment]
> user has to mount the folder

The user needs to mount the folder anyways to access local files (e.g. the BAMs). Docker only provides the computational environment and OS. 

I'll try adding in the phasing files again manually; that's all we can do. I'll note this in the Dockerfile.

**Comment by teng-gao** [comment]
I see. Also it's fine to just provide the hg38 reference, if that makes things easier

**Comment by evanbiederstedt** [comment]
> Also it's fine to just provide the hg38 reference, if that makes things easier

Fair enough; that will make the image smaller. 

Ok, that's what now exists at https://hub.docker.com/r/pkharchenkolab/numbat-rbase

**Comment by teng-gao** [comment]
Tested on TNBC1/ATC2 and works.

**Pull request merged**
