### PR TITLE
Added Rcpp function for forward_back_allele()

### PR DESCRIPTION
**Pull request by evanbiederstedt**
Related PR: https://github.com/kharchenkolab/Numbat/pull/11

See questions in Slack.

### CODE REVIEW

**Comment by evanbiederstedt** [comment]
Discussed on slack, 5 Feb:

Questions put here for `forward_allele()`:

**Q1:** https://github.com/kharchenkolab/numbat/blob/201662f539f748828f4c81bc00b1cbfa8ef14b76/R/hmm.R#L214-L231

I believe this should actually be
```
    for (t in 1:n) {
       
       ....                    
        logalpha[t,] <- logphi + lscale
                          
        ## not here: LL <- lscale
    }
    LL <- lscale
```

Otherwise, there's no reason to redefine `L` each time in the loop. 

**Q2** I'm worried about this; I think it's a bug, as I'm not able to translate the logic of the data structures used into C++. 

What's `forward_back_allele()` meant to return? 

https://github.com/kharchenkolab/numbat/blob/201662f539f748828f4c81bc00b1cbfa8ef14b76/R/hmm.R#L250

```
 p_up = exp(logalpha + logbeta - LL)[,1]
```
 
 Check the dimensions calculated by `exp(logalpha + logbeta - LL)`. You then take the first column, which returns a numeric vector of two values----this procedure doesn't quite make sense to me on a few levels. 
 
 Check the expected returned values for `forward_back_allele()` here in `classify_alleles()`:
 
 https://github.com/kharchenkolab/numbat/blob/f29889761bd0b5fab6436bf5646f596c3ef2dabf/R/utils.R#L789-L795

**Q3:**

I think there's something inconsistent about the indices here: 
https://github.com/kharchenkolab/numbat/blob/201662f539f748828f4c81bc00b1cbfa8ef14b76/R/hmm.R#L237-L248

I think it should actually be:

```
    for (t in seq(n, 1, -1)){
        
        logphi = sapply(1:m, function(i) matrixStats::logSumExp(logphi + logprob[t,] + logPi[[t]][i,]))

        logbeta[t,] <- logphi + lscale

        logsumphi <- matrixStats::logSumExp(logphi)

        logphi <- logphi - logsumphi

        lscale <- lscale + logsumphi
    }    
    
```

**Comment by teng-gao** [comment]
Q1:
seems like you're right - the `LL <- lscale` is outside of the for loop. The two should produce identical results, however. Please confirm. 
https://github.com/cran/HiddenMarkov/blob/master/R/forwardback.R#L15-L23
On another note, trust that you already converted the 1 based index to 0 based index here.

**Comment by teng-gao** [comment]
Q3:
My indices are consistent with original code here. 
https://github.com/cran/HiddenMarkov/blob/master/R/forwardback.R#L39-L45

I think that's just how backward probabilities work. Check page 3 of
http://www.cs.columbia.edu/~mcollins/fb.pdf

**Comment by teng-gao** [comment]
Q2: It's suppose to return a length n vector where n is the number of SNPs for which posteriors need to be calculated. We only take the first column because the two columns should sum to 1 (i.e. we take the probability that the allele is major). `p_up` can be renamed to `p_major` now that we are moving away from the `_up` and `_down` terminology to `_major` and `_minor`..

**Comment by teng-gao** [comment]
Finally, don't worry about completing this if you haven't already because it's not a bottleneck in runtime.

**Comment by evanbiederstedt** [comment]
> Q3:
> My indices are consistent with original code here.
> https://github.com/cran/HiddenMarkov/blob/master/R/forwardback.R#L39-L45

> I think that's just how backward probabilities work - you have them from 1...n-1. Check page 3 of
> http://www.cs.columbia.edu/~mcollins/fb.pdf

@teng-gao 
The details of the forward-backward algorithm made sense, i.e. the recursion/backward part goes from n-1 to 1

Though I guess I overlooked +1 in `prob[i+1,]`

```
for (i in seq(n-1, 1, -1)){
      phi <- Pi %*% (prob[i+1,]*phi)
      logbeta[i,] <- log(phi) + lscale
      sumphi <- sum(phi)
      phi <- phi/sumphi
      lscale <- lscale + log(sumphi)
}
```

Let's assume n = 20

```
for (i in seq(n-1, 1, -1))
```
This outputs 19, 18, 17, ...1. 

`prob[i+1,]` will result in  `prob[20], prob[19], prob[18], ..., prob[2]`

`logbeta[i,] ` will result in `logbeta[19,] , logbeta[18,], logbeta[17,], ...logbeta[1,] `

So this is correct. Understood now.

**Comment by evanbiederstedt** [comment]
See slacks; all variables give the same outputs between the original R code and Rcpp. 

Added some unit tests. 

Please review and merge if happy.

**Comment by hiraksarkar** [comment]
This needs a bit more inspection, I will get back to it. @evanbiederstedt did you see the conflicts?

**Pull request merged**
