### PR TITLE
CRAN clean-up

### PR DESCRIPTION
**Pull request by evanbiederstedt**
Down to 2 Warnings, 5 notes. 

Remaining items:

* Documentation here:

```
Undocumented arguments in documentation object 'analyze_bulk'
  ‘segs_loh’ ‘classify_allele’ ‘run_hmm’ ‘prior’ ‘exclude_neu’
  ‘phasing’ ‘verbose’

Undocumented arguments in documentation object 'cnv_heatmap'
  ‘exclude_gap’

Undocumented arguments in documentation object 'get_bulk'
  ‘min_depth’ ‘lambda’ ‘verbose’

Undocumented arguments in documentation object 'plot_mut_history'
  ‘legend’

Undocumented arguments in documentation object 'plot_phylo_heatmap'
  ‘pal_clone’ ‘exclude_gap’ ‘root_edge’ ‘snvs’ ‘raster’

Undocumented arguments in documentation object 'plot_psbulk'
  ‘exclude_gap’ ‘raster’

Undocumented arguments in documentation object 'run_numbat'
  ‘alpha’ ‘min_overlap’ ‘random_init’ ‘verbose’ ‘min_genes’ ‘p_multi’
  ‘plot’ ‘check_convergence’ ‘exclude_neu’

Functions with \usage entries need to have the appropriate \alias
entries, and all their arguments documented.
The \usage entries must correspond to syntactically valid R code.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

* Documentation of stuff in `data.R`

* Data issue
```
* checking LazyData ... WARNING
  LazyData DB of 152.4 MB without LazyDataCompression set
  See §1.1.6 of 'Writing R Extensions'

```

Read here: https://cran.r-project.org/doc/manuals/R-exts.html#Data-in-packages

### CODE REVIEW

**Comment by teng-gao** [comment]
Hi Evan,

It seems that some essential dependencies are in `Suggested`. Only `matrixStats, testthat, ggrastr, ggrepel, knitr` are non-essential. 

Teng

**Comment by evanbiederstedt** [comment]
@teng-gao 

This is something else we'll need to fix:

```
* checking package dependencies ... NOTE
Imports includes 31 non-default packages.
Importing from so many packages makes the package vulnerable to any of
them becoming unavailable.  Move as many as possible to Suggests and
use conditionally.
```

So I've been moving to Suggests with conditions: https://stackoverflow.com/questions/63345284/r-package-cran-note-for-package-dependencies-and-warnings-in-tests

**Comment by teng-gao** [comment]
Ok. It would make the most sense to do (2) for everything except for `matrixStats, testthat, ggrastr, ggrepel, knitr`, since the main workflow needs those functions to run. Could you take a crack at copying the function?

**Comment by evanbiederstedt** [comment]
@teng-gao 

> Could you take a crack at copying the functions (hopefully we can avoid any copyright issues)?

Yeah, I could do this.

> Ok. It would make the most sense to do (2) for everything except for matrixStats, testthat, ggrastr, ggrepel, knitr, since the main workflow needs those functions to run. 

Given the packages which exist in Imports now, what are libraries whereby you only use 1-2 functions OR you only use those libraries 1-3 times?

**Comment by teng-gao** [comment]
Here's a list I can think of now:
```
Rsamtools::bgzip (probably can replace with command line)
caTools::runmean
gtools::mixedsort
dendextend::get_leaves_attr
VGAM::log1mexp
pryr::mem_used (probably can replace with base R memory functions)
zoo::na.locf
```

**Comment by evanbiederstedt** [comment]
```
Status: 2 NOTEs
```

Everything should be mostly cleaned up, I think. 

Please take a look. Everything should work as expected, but it's possible there are mistakes.

**Comment by evanbiederstedt** [comment]
@teng-gao 

There may have been some miscommunication earlier. It's "Imports" where the complaints were. I guess we need 20 or less. 

We can keep those packages in "Suggests"

I'd like to add `caTools` and `dendextend` back to Imports, as they're tricky to port.....

**Comment by teng-gao** [comment]
Not sure I understand - are these suggested packages installed as dependencies when users install Numbat? These functions I listed above are needed in the main workflow, so wouldn't users have to install them one by one after installing Numbat?

**Comment by evanbiederstedt** [comment]
I did something like 

```
    if (!requireNamespace("caTools", quietly = TRUE)) {
        stop("Package \"caTools\" needed for this function to work. Please install it.", call. = FALSE)
    }
```

I think that won't work for `caTools` and `dendextend` functions....and porting them is a bit of a pain, though possible. 

Darn. 


**Other ideas**
* We could try to write `patchwork` functions using `ggplot2` only. That's one we could remove.....
* `purrr` should go as well, as it's part of `tidyverse`
* It would be nice to replace the `stringr` functions which something else so we could remove this. 
* We might be able to port `ape` stuff as well....but porting this is a pain too.

**Comment by teng-gao** [comment]
These other functions are needed too, unfortunately.  We don't want users to run into these "please install xx package" errors while running the main workflow.

> Here's a list I can think of now:
> 
> ```
> Rsamtools::bgzip (probably can replace with command line)
> caTools::runmean
> gtools::mixedsort
> dendextend::get_leaves_attr
> VGAM::log1mexp
> pryr::mem_used (probably can replace with base R memory functions)
> zoo::na.locf
> ```

**Comment by teng-gao** [comment]
> I did something like
> 
> ```
>     if (!requireNamespace("caTools", quietly = TRUE)) {
>         stop("Package \"caTools\" needed for this function to work. Please install it.", call. = FALSE)
>     }
> ```
> 
> I think that won't work for `caTools` and `dendextend` functions....and porting them is a bit of a pain, though possible.
> 
> Darn.
> 
> **Other ideas**
> 
> * We could try to write `patchwork` functions using `ggplot2` only. That's one we could remove.....
> * `purrr` should go as well, as it's part of `tidyverse`
> * It would be nice to replace the `stringr` functions which something else so we could remove this.
> * We might be able to port `ape` stuff as well....but porting this is a pain too.

`purrr` is easy to replace with some `lapply` one-liners.  `stringr` `ape` `patchwork` are harder because they are used extensively.

**Comment by teng-gao** [comment]
Also please test the current version using the `ATC2` example - it's a small dataset that takes 5 min to run.

**Comment by evanbiederstedt** [comment]
`purrr` can be safely removed from `Imports` as I did `tidyverse`

> pryr::mem_used (probably can replace with base R memory functions)

This is outdated; it's `lobstr` now....

> caTools::runmean

This was annoying to port, as it's a method with all this C code. Could this be rewritten on our end?

> gtools::mixedsort

This could be easily ported. 


> dendextend:

Surprisingly a lot here.....might have to keep. 

> VGAM::log1mexp

This we could port


RE: zoo

I ported this, so that's resolved.

**Comment by teng-gao** [comment]
RE: runmean
I wouldn't bother, as implementing it ourselves might change the results ..
RE: patchwork
The hard part about arranging plots is the axis alignment. I would be surprised if you can find an easy replacement for doing so. It's non-trivial.

Porting the other functions sounds good (what do you mean by port?)

**Comment by teng-gao** [comment]
Have you checked if the package works using the ATC2 example?

```
Error in summarise(., n = length(unique(GT))) : 
  could not find function "summarise"
Calls: run_numbat -> check_allele_df -> %>%
Execution halted
```

**Comment by evanbiederstedt** [comment]
I'll revise, given there have been so many changes to `devel`

**Pull request closed without merging**
